name: kicksvibe
description: "KicksVibe - A modern e-commerce application for shoes built with Flutter and Firebase."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.9
  equatable: ^2.1.0
  google_fonts: ^8.2.1
  shared_preferences: ^2.5.5
  firebase_auth: 6.5.7
  flutter_bloc: ^9.1.1
  firebase_core: 4.13.0
  google_sign_in: ^7.2.0
  cloud_firestore: 6.8.0
  get_it: ^9.2.1
  injectable: ^3.0.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  cached_network_image: ^3.4.1
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  dio: ^5.11.0
  webview_flutter: ^4.14.1
  firebase_messaging: ^16.5.0
  shimmer: ^4.0.0

dev_dependencies:
  feature_generator: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.0
  injectable_generator: ^3.0.0
  hive_ce_generator: ^1.11.1
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"

dependency_overrides:
  get_it: ^9.2.1
  injectable: ^3.0.0
