// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKIj9AzF3nxJdwRsgpdz83txKKUi79Iv0',
    appId: '1:323518590304:web:2588a3cdd5db618aad0205',
    messagingSenderId: '323518590304',
    projectId: 'shoesstore-4e48b',
    authDomain: 'shoesstore-4e48b.firebaseapp.com',
    storageBucket: 'shoesstore-4e48b.firebasestorage.app',
    measurementId: 'G-5Q5MHEPRCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnbcWePH52V9-wySjaL7Kjmtqe2mqX1U',
    appId: '1:323518590304:android:13b23a8e3a6b77f4ad0205',
    messagingSenderId: '323518590304',
    projectId: 'shoesstore-4e48b',
    storageBucket: 'shoesstore-4e48b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2s1FjzOvJ_-T6XVP45MmcbyhaN2b6kws',
    appId: '1:323518590304:ios:e9128555374d1f95ad0205',
    messagingSenderId: '323518590304',
    projectId: 'shoesstore-4e48b',
    storageBucket: 'shoesstore-4e48b.firebasestorage.app',
    androidClientId:
        '323518590304-e9u2ghbptn6f8321djmduadnqb7kmlbr.apps.googleusercontent.com',
    iosClientId:
        '323518590304-4ivnpqml1328a7n9dk8ds9imaln9diut.apps.googleusercontent.com',
    iosBundleId: 'com.example.kicksvibe',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2s1FjzOvJ_-T6XVP45MmcbyhaN2b6kws',
    appId: '1:323518590304:ios:e9128555374d1f95ad0205',
    messagingSenderId: '323518590304',
    projectId: 'shoesstore-4e48b',
    storageBucket: 'shoesstore-4e48b.firebasestorage.app',
    androidClientId:
        '323518590304-e9u2ghbptn6f8321djmduadnqb7kmlbr.apps.googleusercontent.com',
    iosClientId:
        '323518590304-4ivnpqml1328a7n9dk8ds9imaln9diut.apps.googleusercontent.com',
    iosBundleId: 'com.example.kicksvibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKIj9AzF3nxJdwRsgpdz83txKKUi79Iv0',
    appId: '1:323518590304:web:c0591c8a0c47e403ad0205',
    messagingSenderId: '323518590304',
    projectId: 'shoesstore-4e48b',
    authDomain: 'shoesstore-4e48b.firebaseapp.com',
    storageBucket: 'shoesstore-4e48b.firebasestorage.app',
    measurementId: 'G-4T7FW449M0',
  );
}
