// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:kicksvibe/features/cart/data/models/cart_item_model.dart';
import 'package:kicksvibe/features/home/data/models/brand_model.dart';
import 'package:kicksvibe/features/home/data/models/product_model.dart';
import 'package:kicksvibe/features/notifications/data/models/NotificationModel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BrandModelAdapter());
    registerAdapter(CartItemModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(ProductModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BrandModelAdapter());
    registerAdapter(CartItemModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(ProductModelAdapter());
  }
}
